name: react-18
on:
  push:
    branches: [react-18]
  pull_request:
    branches: [react-18]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.20.3

      - name: Build site
        run: root=https://react-18.deno.dev deno run -A https://deno.land/x/ultra@v0.8.0/src/deno/build.ts

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: react-18
          entrypoint: ULTRA.js
          root: .ultra
